--- # file creation
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes
  gather_facts: yes


  tasks:
    - name: creating a file
      file:
        path: /home/ansible/demofile
        state: touch

