--- # create user playbook
- name: my test playbook
  hosts: all
  become: yes
  connection: ssh
  user: ansible
  gather_facts: yes
  tasks:
    - name: creating a user
      user:
        name: teja1996
