--- # Loop Playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
   - name: add a list of users
     user: name='{{ item }}' state=present
     with_items:
        - Raj
        - Sai
        - Hari

